version: '3.8'

services:
  maestro:
    image: mariadb:10.11
    container_name: maestro
    hostname: maestro
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: lab_db
    ports:
      - "3306:3306"
    volumes:
      - ./conf/master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      - db_network

  la_nueva:
    image: mariadb:10.11
    container_name: la_nueva
    hostname: la_nueva
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./conf/replica1.cnf:/etc/mysql/conf.d/replica.cnf
    networks:
      - db_network
    depends_on:
      - maestro

  la_ex:
    image: mariadb:10.11
    container_name: la_ex
    hostname: la_ex
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - ./conf/replica2.cnf:/etc/mysql/conf.d/replica.cnf
    networks:
      - db_network
    depends_on:
      - maestro

  api:
    image: node:18-alpine
    container_name: api-replicas
    working_dir: /app
    volumes:
      - ../api:/app
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - db_network
    depends_on:
      - maestro
      - la_nueva
      - la_ex

networks:
  db_network:
    driver: bridge
